### ISSUE TITLE
required third party packages list

### ISSUE THREAD

**Issue by cridder** [bimone/scripts-dynamo#1]
is there a list of required third party packages?
specifically for rename almost all.
revit 2022,
out of the box dynamo version 2.x
thanks

**Comment by jmcouffin** [comment]
Hi, only dependency here is 
![image](https://user-images.githubusercontent.com/7872003/224644636-ee4a2f4d-18f1-4e29-abc9-1a12580a501f.png)
I used to have a version without dependency at all but cannot get a hold on to it.

**Comment by cridder** [comment]
perfect.  thanks so much
