### ISSUE TITLE
Map Global Parameters doesn't open Multiple Input Forms

### ISSUE THREAD

**Issue by bwajp** [bimone/scripts-dynamo#2]
Revit 2023, data-shapes 2022.2.103 (also tested with 2025.3.118, and 2023.2.112), orchid 202.4.2.7024

Running the script doesn't open any multiple input forms, just open a window called "Dynamo For Revit - Processed elements" which says 
"None Processed elements
1 Elements not processed"

**Comment by jmcouffin** [comment]
@bwajp 
Hi, 
Thanks for the heads up.
We will probably get ride of this tool and add it to pyRevit.
Maintaining dynamo script has been such a nightmare over the past few years as we partly relied on others packages and Dynamo changes and also Revit api changes that we decided to start coding actual tools with pyRevit and python.
I will close this issue but put it in my backlog and let you know here once it is included in pyRevit
